server:
  port: 8310

spring:
  application:
    name: abacus-ms-edi-kra-invoice-claims
  profiles:
    active: default
    
#spring.jpa.properties.hibernate.jdbc.batch_size=5

  jpa:
    show-sql: true   
    hibernate:
      ddl-auto: none
      jdbc:
        batch_size: 50

    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

  # datasource:
  #   driver:
  #     class: oracle.jdbc.driver.OracleDriver
  #   url: ${integ.datasource.url}
  #   username: ${integ.datasource.username}
  #   password: ${integ.datasource.password}

  cloud:
    config:
      #label: master
      fail-fast: true
      retry:
        max-attempts: 5
        max-interval: 1500
        multiplier: 1.5
      discovery:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false

integ:
  datasource:
    jdbc-url: ${integ.datasource.url}
    username: ${integ.datasource.username}
    password: ${integ.datasource.password}
    driver-class-name: oracle.jdbc.driver.OracleDriver

abacus:
  datasource:
    jdbc-url: ${abacus.prod.datasource.url}
    username: ${abacus.prod.datasource.username}
    password: ${abacus.prod.datasource.password}
    driver-class-name: oracle.jdbc.driver.OracleDriver
    
aar:
  datasource:
    jdbc-url: jdbc:sqlserver://192.180.3.14:7004 
    #${aar.datasource.url}
    username: ${aar.datasource.username}
    password: ${aar.datasource.password}
    datasource.member.driverClassName: ${aar.datasource.driverClassName}
#    com.mysql.cj.jdbc.Driver
#    driver-class-name: oracle.jdbc.driver.OracleDriver


eureka:
  #registryFetchIntervalSeconds: 1 #COMMENT THIS IN PRODUCTION
  client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        #  defaultZone: http://192.180.4.15:8889/eureka
#         defaultZone: http://127.0.0.1:8889/eureka
        defaultZone: http://smart:smart123@192.180.4.22:8103/eureka/
      instance:
        preferIpAddress: true        
        #hostname: localhost
        #lease-renewal-interval-in-seconds: 300
  instance:
    #leaseRenewalIntervalInSeconds: 1  #COMMENT THIS IN PRODUCTION
  ribbon:
    #ServerListRefreshInterval: 1000   #COMMENT THIS IN PRODUCTION


management:
  #context-path: /admin
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      base-path: /actuator
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*' 


logging:
  file: {spring.application.name}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: INFO
      type:
        decriptor:
          sql:
            BasicBinder: TRACE
    com:
      netflix:
        loadbalancer: info   

springdoc:
  packagesToScan: com.smart.integ.controller;
  version: 1.5.8




