server:
  port: 8090

spring:
  application:
    name: jubilee-microservice
  profiles:
    active: default
  
  jpa:
    show-sql: true   
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect

  # datasource:
  #   driver:
  #     class: oracle.jdbc.driver.OracleDriver
  #   url: ${integ.datasource.url}
  #   username: ${integ.datasource.username}
  #   password: ${integ.datasource.password}

  cloud:
    config:
      #label: master
      fail-fast: true
      retry:
        max-attempts: 5
        max-interval: 1500
        multiplier: 1.5
      discovery:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false

integ:
  datasource:
    jdbc-url: ${integ.datasource.url}
    username: ${integ.datasource.username}
    password: ${integ.datasource.password}
    driver-class-name: oracle.jdbc.driver.OracleDriver

abacus:
  datasource:
    jdbc-url: ${abacus.datasource.url}
    username: ${abacus.datasource.username}
    password: ${abacus.datasource.password}
    driver-class-name: oracle.jdbc.driver.OracleDriver

eureka:
  #registryFetchIntervalSeconds: 1 #COMMENT THIS IN PRODUCTION
  client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://192.180.3.78:8761/eureka
      instance:
        preferIpAddress: true        
        #hostname: localhost
        #lease-renewal-interval-in-seconds: 300
  instance:
    #leaseRenewalIntervalInSeconds: 1  #COMMENT THIS IN PRODUCTION
  ribbon:
    #ServerListRefreshInterval: 1000   #COMMENT THIS IN PRODUCTION


management:
  #context-path: /admin
  endpoint:
    health:
      enabled: true
      show-details: always
    shutdown:
      enabled: false
  endpoints:
    web:
      base-path: /actuator
      # By default, only 'health' and 'info' are accessible via web
      exposure:
        include: '*' 


logging:
  file: jubilee-microservice.log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'
  level:
    org:
      hibernate:
        SQL: INFO
      type:
        decriptor:
          sql:
            BasicBinder: TRACE
    com:
      netflix:
        loadbalancer: info   
